import 'package:firedart/auth/firebase_auth.dart'; ///Library yang menyediakan dukungan untuk otentikasi Firebase.
import 'package:flutter/material.dart'; /// Library utama untuk pembuatan antarmuka pengguna (UI) di Flutter.
import 'package:get/get.dart'; ///Library untuk manajemen state dan navigasi di Flutter.
import 'package:hive_flutter/hive_flutter.dart'; /// untuk manajemen database lokal menggunakan Hive, yang merupakan database NoSQL ringan.
import 'hive_store.dart';
import 'start_page.dart';
import 'token_adapter.dart';

const apiKey = "AIzaSyDazyO52aRtQE6C6JbVXblfSFxwmMMKP3Y";
const projectId = "cobaduluya-13fc5";

/// untuk menjalankan aplikasi
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Hive.initFlutter();
  Hive.registerAdapter(TokenAdapter());

  FirebaseAuth.initialize(apiKey, (await HiveStore.create()));

  runApp(const MyApp());
}

// Explanation of what the query code is for
//what will be generated by this query when run
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const StartPage(),
    );
  }
}
